# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-f04f0308-f965-4ae9-8638-b5b7dd33fd11";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-f04f0308-f965-4ae9-8638-b5b7dd33fd11".device = "/dev/disk/by-uuid/f04f0308-f965-4ae9-8638-b5b7dd33fd11";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-f04f0308-f965-4ae9-8638-b5b7dd33fd11";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-f04f0308-f965-4ae9-8638-b5b7dd33fd11";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9AC3-79AD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-36ef4bf1-ada5-4406-84c3-9d82e16f0d68"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
